config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers, controllers: {
    sessions: 'trainers/sessions',
    registrations: 'trainers/registrations'
}

  authenticated :trainer do
    root to: 'trainers#index', as: :trainer_root
    
  end
  
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
 
  authenticated :user do
    root to: 'users#index', as: :user_root
  end

  resources :trainers 

  resources :users

  resources :chats, only: [:index, :new, :create, :show] do
    resources :messages, only: [:index, :new, :create]
  end

  resources :reservations, only: [:index, :new, :create]
  
  root 'pages#home'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<div class="account-selection">
  <div class="option-group">
    <h2>   出張パーソナルトレーニングご利用の方はこちら</h2>
    <div class="links">
      <%= link_to "Sign up", new_user_registration_path, class:"signup-link" %>
      <%= link_to "Sign in", new_user_session_path, class:"signin-link" %>
    </div>
  </div>
  <div class="option-group">
    <div class="box">
      <h3>トレーナー希望(理学療法士)の方はこちら</h3>
      <div class="links">
        <%= link_to "Sign up", new_trainer_registration_path, class:"signup-link" %>
        <%= link_to "Sign in", new_trainer_session_path, class:"signin-link" %>
      </div>
    </div>
  </div>
</div>