config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers, controllers: {
    sessions: 'trainers/sessions',
    registrations: 'trainers/registrations'
}

  authenticated :trainer do
    root to: 'trainers#index', as: :trainer_root
    
  end
  
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
 
  authenticated :user do
    root to: 'users#index', as: :user_root
  end

  resources :trainers 

  resources :users

  resources :chats, only: [:index, :new, :create, :show] do
    resources :messages, only: [:index, :new, :create]
  end

  resources :reservations, only: [:index, :new, :create]
  
  root 'pages#home'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations
  has_many :reviews
  has_many :chats
  has_many :messages, through: :chats
  has_one_attached :profile_image
  belongs_to :gender
  belongs_to :prefecture

  with_options presence: true do
    validates :nickname
    validates :email, uniqueness: true
    validates :encrypted_password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,}+\z/i }
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龠々ー]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龠々ー]+\z/ }
    validates :last_name_reading, format: { with: /\A[ぁ-んー]+\z/ }
    validates :first_name_reading, format: { with: /\A[ぁ-んー]+\z/ }
    validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :gender_id
    validates :prefecture_id
    validates :city
    validates :registration_number, format: { with: /\A\d{6}\z/ }
    validates :career
    validates :profile
  end
end

app/controllers/trainers/registrations_controller.rb
class Trainers::RegistrationsController < Devise::RegistrationsController
  def new
    @trainer = Trainer.new
  end

  def create
    @trainer = Trainer.new(trainer_params)
    if @trainer.save
      sign_in(@trainer)
      redirect_to after_sign_up_path_for(@trainer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  protected

  def after_sign_up_path_for(resource)
    trainer_root_path
  end

  def after_sign_in_path_for(resource)
    trainer_root_path
  end


  private

  def trainer_params
    params.require(:trainer).permit(:profile_image, :nickname, :email, :password, :password_confirmation, :last_name, :first_name, :last_name_reading, :first_name_reading, :age, :gender_id, :prefecture_id, :city, :registration_number, :career, :profile)
  end
end

app/controllers/trainers/sessions_controller.rb
# frozen_string_literal: true

class Trainers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @reservations = Reservation.where(trainer_id: current_trainer.id)
  end
  
  def show
    @trainer = Trainer.find(params[:id])  
  end



  private
  
  def after_sign_in_path_for(resource)
    trainer_root_path
  end

end

app/helpers/trainer/registrations_helper.rb
module Trainer::RegistrationsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/index.html.erb
<h1>予約リクエスト一覧</h1>

<% if @reservations.present? %>
  <table class="reservation-table">
    <thead>
      <tr>
        <th>日付</th>
        <th>時間</th>
        <th>姓</th>
       
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= reservation.date %></td>
          <td><%= ReservationTime.find(reservation.time_id).name %></td>
          <td><%= reservation.last_name %></td>
          <td><%= reservation.first_name %></td>
          <td>
            <%= link_to "承認する", "#", method: :post, class: "btn-approve" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-reservations">予約リクエストはありません</div>
<% end %>

app/views/trainers/show.html.erb
<div class="main">
 <div class="inner">
  <div class="user__wrapper">
   <h2 class="page-heading">トレーナー自己紹介</h2>

  <div class="profile-image-wrapper">
  <%= image_tag @trainer.profile_image.variant(resize: "300x300"),class: "profile-image" %>
  </div>

<table class="table">
 <tbody>
  <tr>
   <th class="table__col1">ニックネーム</th>
   <td class="table__col2"><%= @trainer.nickname %></td>
  </tr>
  <tr>
   <th class="table__col1">名前</th>
   <td class="table__col2"><%= "#{@trainer.last_name} #{@trainer.first_name}&nbsp;&nbsp;&nbsp;&nbsp;(#{@trainer.last_name_reading} #{@trainer.first_name_reading})".html_safe%></td>
  </tr>
  <tr>
   <th class="table__col1">年齢/性別</th>
   <td class="table__col2"><%= "#{@trainer.age}歳 / #{@trainer.gender.name}" %></td>
  </tr>
  <tr> 
   <th class="table__col1">活動エリア</th>
   <td class="table__col2"><%= "#{@trainer.prefecture.name} #{@trainer.city}" %></td>
  </tr>
  <tr> 
   <th class="table__col1">理学療法士 <br>免許登録番号</th>
   <td class="table__col2"><%= @trainer.registration_number %></td>
  </tr>
  <tr> 
   <th class="table__col1">経歴</th>
   <td class="table__col2"><%= @trainer.career %></td>
  </tr>
  <tr> 
   <th class="table__col1">自己紹介</th>
   <td class="table__col2"><%= @trainer.profile %></td>
  </tr>
 </tbody>
</table>

<div class="button-wrapper">
<% if user_signed_in? %>
  <%= link_to '予約する', new_reservation_path(trainer_id: @trainer.id), class: 'action-button' %>
  <%= link_to 'ダイレクトメッセージを送る', chats_path(trainer_id: @trainer.id),data: { turbo_method: :post }, class: 'action-button' %>
<% end %>
</div>

  </div>
 </div>
</div>