config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers, controllers: {
    sessions: 'trainers/sessions',
    registrations: 'trainers/registrations'
}

  authenticated :trainer do
    root to: 'trainers#index', as: :trainer_root
    
  end
  
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
 
  authenticated :user do
    root to: 'users#index', as: :user_root
  end

  resources :trainers 

  resources :users

  resources :chats, only: [:index, :new, :create, :show] do
    resources :messages, only: [:index, :new, :create]
  end

  resources :reservations, only: [:index, :new, :create]
  
  root 'pages#home'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhysiofitPro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header> 
      <div class="logo">
         <%= link_to image_tag("physiofit-pro-logo.png", class:"php-icon"), "/" %>
      </div> 
      <nav> 
       <% if trainer_signed_in? || user_signed_in? %>
          <%= link_to "My page", trainer_signed_in? ? trainer_path(current_trainer.id) : user_path(current_user.id) %>
          <%= link_to "Message", chats_path %>
          <% if trainer_signed_in? %>
             <%= link_to "Sign out", destroy_trainer_session_path, data: {turbo_method: :delete}%>
          <% else %>
             <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete} %>
          <% end %>
      <% end %>
      </nav> 
    </header>

    <div class = "common-content">
      <%= yield %>
    </div>

    <footer> 
      <p>&copy; 2024 <a href="/">PhysioFit Pro</a>. All Rights Reserved.</p> 
    </footer> 
  </body>
</html>